name: CI workflow

on:
  push:
  pull_request:
    branches:
      - main
#main_worklow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install App dependencies
      run: npm install

    - name: Build the app
      run:
        npm run build